version: '2.4'
services:
  map:
    build:
      context: ./map/
    env_file: ./map/envi.conf
    ports:
      - "8585:80"
    links:
      - pokealarm

  mad_walker:
    build:
      context: ./Map-A-Droid/
    command: "startWalker.py -os"
    volumes:
      - ./Map-A-Droid:/usr/src/app/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    cpus: 2.0
    network_mode: "host"

  mad_screenshot:
    build:
      context: ./Map-A-Droid/
    command: "startWalker.py -oo"
    volumes:
       - ./Map-A-Droid:/usr/src/app/
       - "/etc/timezone:/etc/timezone:ro"
       - "/etc/localtime:/etc/localtime:ro"
    restart: always
    cpus: 2.0
    links:
      - pokealarm

  mad_admin:
    build:
      context: ./Map-A-Droid/
    volumes:
       - ./Map-A-Droid:/usr/src/app/
       - "/etc/timezone:/etc/timezone:ro"
       - "/etc/localtime:/etc/localtime:ro"
    restart: always
    ports:
      - "127.0.0.1:5000:5000"


  pokealarm:
    build:
      context: ./pokealarm/
    restart: always
    ports:
      - "127.0.0.1:4000:4000"









  


